### ISSUE TITLE
Password bypass

### ISSUE THREAD

**Issue by Mget74** [2bllw8/anemo#15]
I noticed I can unlock/mount Anemo by tapping the tile or icon to put in the password, but if I click Configuration - Allow Storage Access on - then click the back key it unlocks without entering a password. 

I haven't gotton a chance to test it but a few times, I like the design of it but noticed it's not useful for Rooted phones and thought that may be a reason for this. 
Picked up a cheap LG i never use as it has a stock rom and installed Anemo to test, Im able to bypass the password on it as well. 
It seems 

I assume Storage Access is what allows the files app to manage it? instead of just being able to share to it?

Keep up the nice work, even though my main/only device atm is rooted, i am keeping it installed to see the progress of it. I feel like it's a app with an original idea along with being basic/simple as it should be. I don't think it's completely useless on a rooted rom either, there's always a use for something.

**Comment by 2bllw8** [comment]
Hi, thanks for submitting this!

> noticed it's not useful for Rooted phones

Yes, the app does handle rooted devices security (also #5): even if there were additional encryption layers other than those provided by the OS, on a rooted device they'd be very easy to bypass. It's something not worth spending time on.

>  click Configuration - Allow Storage Access on - then click the back key it unlocks

I also noticed this after releasing 2.1: it's something that will be addressed for 2.2 since I want to improve the password lock feature (see also #10 and #11).

**Comment by Droidphilev** [comment]
Hi all and thanks for this app

+1 for the password bypass on  a Oneplus 9 pro stock Android 12, not rooted.

**Comment by 2bllw8** [comment]
Fixed with commit cd939e1
