### ISSUE TITLE
[Feature request] rounded corners

### ISSUE THREAD

**Issue by Wjxfi** [2bllw8/anemo#38]
![Polish_20221028_231544303.jpg](https://user-images.githubusercontent.com/113500363/198724477-d3a24da9-36fc-435e-afb6-9827300479a9.jpg)

You have a square window, can you make it like in the next picture?

![277659.jpg](https://user-images.githubusercontent.com/113500363/198722338-b10f16fe-891d-4a7d-a20a-c720d9263bb8.jpg)

Not only in this place. in the pop-up window if the password is not correct, and in other places as well

It would make the design much better

**Comment by 2bllw8** [comment]
The corner radius is taken from your device's "system windows" corner radius. It's a value the operative system provides to apps so that they can match the physical display corners and create an harmonised UI. I'd suggest you check for updates of your OS to see if the manufacturer has added such information. Otherwise if you're running a custom ROM you may contact the developer and ask them to supply such information in the device configuration files.
